name: Publish

on:
  push:
    tags:
      - '*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build zip file
        run: npm run build
        
      - name: Create ZIP file
        run: zip -r release.zip ./dist # 빌드된 파일이 있는 디렉토리를 압축
        
      - name: Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: 'upload' 
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
          zip_file: 'release.zip'
